<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\Kegiatan;
use App\Models\Kak;
use App\Models\Rab;
use App\Models\IndikatorKak;
use App\Models\LogStatus;
use Database\Seeders\MasterDataSeeder;
use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\TestDox;
use Tests\TestCase;

class UsulanTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        // Seed master data and roles/permissions
        $this->seed(MasterDataSeeder::class);
        $this->seed(RolePermissionSeeder::class);
    }

    /**
     * Test successful KAK/proposal submission by Admin.
     */
    #[Test]
    #[TestDox('Memastikan usulan baru berhasil disimpan dan diajukan oleh Admin dengan data RAB JSON dan indikator flat')]
    public function test_kegiatan_submission_succeeds(): void
    {
        // 1. Create an Admin user
        $admin = User::create([
            'nama'         => 'Admin Test',
            'email'        => 'admintest@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $admin->assignRole('Admin');

        // 2. Prepare mock request payload matching the HTML form output
        // rab_data is a JSON string as generated by javascript
        $rabDataJson = json_encode([
            'Belanja Barang' => [
                [
                    'uraian' => 'Kertas A4',
                    'rincian' => '1 Rim',
                    'vol1' => 1,
                    'sat1' => 'Rim',
                    'vol2' => 1,
                    'sat2' => 'Rim',
                    'harga' => 50000
                ]
            ],
            'Belanja Jasa' => [
                [
                    'uraian' => 'Honor Pemateri',
                    'rincian' => '1 Orang',
                    'vol1' => 1,
                    'sat1' => 'Orang',
                    'vol2' => 1,
                    'sat2' => 'Orang',
                    'harga' => 500000
                ]
            ]
        ]);

        $payload = [
            'nama_kegiatan' => 'Workshop UI/UX Modern 2026',
            'prodi' => 'D4 Teknik Informatika',
            'nama_pengusul' => 'Admin Test',
            'nim_nip' => '19200388273',
            'jurusan' => 'Teknik Informatika dan Komputer',
            'wadir_tujuan' => 1,
            'indikator_kinerja' => 'Meningkatkan keterampilan mahasiswa',
            'gambaran_umum' => 'Deskripsi gambaran umum kegiatan workshop UI/UX.',
            'penerima_manfaat' => 'Mahasiswa Teknik Informatika',
            'metode_pelaksanaan' => 'Offline di Aula Gedung Q',
            'tahapan' => [
                'Persiapan panitia',
                'Pelaksanaan workshop',
                'Evaluasi dan LPJ'
            ],
            // Flat indicators from repeater inputs
            'indikator_nama' => [
                'Tingkat kehadiran peserta',
                'Tingkat kepuasan peserta'
            ],
            'indikator_bulan' => [
                1,
                2
            ],
            'indikator_target' => [
                90,
                85
            ],
            // Budget data serialized as JSON string
            'rab_data' => $rabDataJson
        ];

        // 3. Post to store route simulating custom session authentication
        $response = $this->withSession([
            'user_id' => $admin->user_id,
            'role' => 'admin'
        ])->post('/admin/pengajuan-usulan/store', $payload);

        // 4. Assert response redirect to usulan index with success message
        $response->assertRedirect(route('admin.usulan.index'));
        $response->assertSessionHas('success_message', 'Usulan berhasil diajukan!');

        // 5. Assert Kegiatan was stored successfully
        $kegiatan = Kegiatan::where('nama_kegiatan', 'Workshop UI/UX Modern 2026')->first();
        $this->assertNotNull($kegiatan);
        $this->assertEquals($admin->user_id, $kegiatan->user_id);
        $this->assertEquals('D4 Teknik Informatika', $kegiatan->prodi_penyelenggara);

        // 6. Assert KAK is stored
        $kak = Kak::where('kegiatan_id', $kegiatan->kegiatan_id)->first();
        $this->assertNotNull($kak);
        $this->assertEquals('Deskripsi gambaran umum kegiatan workshop UI/UX.', $kak->gambaran_umum);

        // 7. Assert Tahapan Pelaksanaan is stored
        $this->assertDatabaseHas('tahapan_pelaksanaans', [
            'kak_id' => $kak->kak_id,
            'nama_tahapan' => 'Pelaksanaan workshop'
        ]);

        // 8. Assert Indikator Keberhasilan is correctly populated from flat array mapping
        $this->assertDatabaseHas('indikator_kaks', [
            'kak_id' => $kak->kak_id,
            'indikator_keberhasilan' => 'Tingkat kehadiran peserta',
            'bulan' => 1,
            'target_persen' => 90
        ]);
        $this->assertDatabaseHas('indikator_kaks', [
            'kak_id' => $kak->kak_id,
            'indikator_keberhasilan' => 'Tingkat kepuasan peserta',
            'bulan' => 2,
            'target_persen' => 85
        ]);

        // 9. Assert RAB items are stored correctly from decoded JSON
        $this->assertDatabaseHas('rabs', [
            'kak_id' => $kak->kak_id,
            'uraian' => 'Kertas A4',
            'harga' => 50000,
            'total_harga' => 50000
        ]);
        $this->assertDatabaseHas('rabs', [
            'kak_id' => $kak->kak_id,
            'uraian' => 'Honor Pemateri',
            'harga' => 500000,
            'total_harga' => 500000
        ]);

        // 10. Assert submission log is added to log_statuses
        $this->assertDatabaseHas('log_statuses', [
            'user_id' => $admin->user_id,
            'tipe_log' => 'SUBMISSION',
            'status' => 'BELUM_DIBACA',
            'id_referensi' => $kegiatan->kegiatan_id
        ]);
    }

    /**
     * Test verifikator approval action saves KAK and MAK code correctly.
     */
    #[Test]
    #[TestDox('Memastikan verifikator berhasil menyetujui usulan, menyimpan kode MAK, dana disetujui, dan memajukan workflow')]
    public function test_verifikator_telaah_approve_works(): void
    {
        // 1. Create users
        $admin = User::create([
            'nama'         => 'Pengusul TI',
            'email'        => 'pengusul@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $admin->assignRole('Admin');

        $verifikator = User::create([
            'nama'         => 'Verifikator TI',
            'email'        => 'verifikator@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $verifikator->assignRole('Verifikator');

        // 2. Create a mock Kegiatan at verifikator position
        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => 'Seminar Cloud Computing 2026',
            'prodi_penyelenggara' => 'D4 Teknik Informatika',
            'pemilik_kegiatan' => 'Pengusul TI',
            'nim_pelaksana' => '19200388273',
            'user_id' => $admin->user_id,
            'jurusan_penyelenggara' => 'Teknik Informatika dan Komputer',
            'status_utama_id' => \App\Services\WorkflowService::STATUS_MENUNGGU,
            'wadir_tujuan' => 1,
            'posisi_id' => \App\Services\WorkflowService::POSITION_VERIFIKATOR,
        ]);

        $kak = Kak::create([
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'iku' => 'Meningkatkan IKU 1',
            'gambaran_umum' => 'Deskripsi.',
            'metode_pelaksanaan' => 'Online',
        ]);

        // 3. Post as verifikator to store endpoint with approval action
        $payload = [
            'action' => 'approve',
            'kode_mak' => 'MAK-TIK-2026-99',
            'dana_disetujui' => 2500000,
            'umpan_balik_verifikator' => 'Usulan lengkap, disetujui untuk diteruskan ke Wadir.'
        ];

        $response = $this->withSession([
            'user_id' => $verifikator->user_id,
            'role' => 'verifikator'
        ])->post("/verifikator/telaah/store/{$kegiatan->kegiatan_id}", $payload);

        // 4. Assert response redirect to verifikator index
        $response->assertRedirect(route('verifikator.telaah.index'));
        $response->assertSessionHas('success', 'Telaah berhasil disimpan.');

        // 5. Assert database updates are saved correctly
        $kegiatan->refresh();
        $this->assertEquals('MAK-TIK-2026-99', $kegiatan->bukti_mak);
        $this->assertEquals(2500000, $kegiatan->dana_di_setujui);
        $this->assertEquals('Usulan lengkap, disetujui untuk diteruskan ke Wadir.', $kegiatan->umpan_balik_verifikator);
        
        // Next workflow position is self::POSITION_ADMIN (1) (goes back to Admin to fill details)
        $this->assertEquals(\App\Services\WorkflowService::POSITION_ADMIN, $kegiatan->posisi_id);
        
        // Status becomes self::STATUS_TELAH_DIVERIFIKASI (7) when moving along
        $this->assertEquals(\App\Services\WorkflowService::STATUS_TELAH_DIVERIFIKASI, $kegiatan->status_utama_id);

        // 6. Assert progress history was saved with the verifikator's user ID
        $this->assertDatabaseHas('progress_histories', [
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'status_id' => \App\Services\WorkflowService::STATUS_TELAH_DIVERIFIKASI,
            'changed_by_user_id' => $verifikator->user_id
        ]);

        // 7. Assert an APPROVAL notification log is added to log_statuses for the owner
        $this->assertDatabaseHas('log_statuses', [
            'user_id' => $admin->user_id,
            'tipe_log' => 'APPROVED',
            'status' => 'BELUM_DIBACA',
            'id_referensi' => $kegiatan->kegiatan_id
        ]);
    }

    /**
     * Test PPK and Wadir approval resets active status to STATUS_MENUNGGU (1) under Opsi 2.
     */
    #[Test]
    #[TestDox('Memastikan persetujuan PPK dan Wadir mereset status usulan ke Menunggu (1) pada meja berikutnya')]
    public function test_ppk_and_wadir_approval_resets_status_to_menunggu(): void
    {
        // 1. Create users
        $admin = User::create([
            'nama'         => 'Pengusul TI',
            'email'        => 'pengusul2@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $admin->assignRole('Admin');

        $ppk = User::create([
            'nama'         => 'PPK TI',
            'email'        => 'ppk@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $ppk->assignRole('PPK');

        $wadir = User::create([
            'nama'         => 'Wadir TI',
            'email'        => 'wadir@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $wadir->assignRole('Wadir');

        // 2. Create a mock Kegiatan at PPK position
        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => 'Pencairan Seminar 2026',
            'prodi_penyelenggara' => 'D4 Teknik Informatika',
            'pemilik_kegiatan' => 'Pengusul TI',
            'nim_pelaksana' => '19200388273',
            'user_id' => $admin->user_id,
            'jurusan_penyelenggara' => 'Teknik Informatika dan Komputer',
            'status_utama_id' => \App\Services\WorkflowService::STATUS_MENUNGGU,
            'wadir_tujuan' => 1,
            'posisi_id' => \App\Services\WorkflowService::POSITION_PPK,
        ]);

        // 3. Post as PPK to store simulating PPK approval
        $response = $this->withSession([
            'user_id' => $ppk->user_id,
            'role' => 'ppk'
        ])->post("/ppk/kegiatan/store/{$kegiatan->kegiatan_id}", ['action' => 'approve']);

        $response->assertRedirect(route('ppk.dashboard'));
        $kegiatan->refresh();

        // Position advances to WADIR (4)
        $this->assertEquals(\App\Services\WorkflowService::POSITION_WADIR, $kegiatan->posisi_id);
        // Active status is reset to STATUS_MENUNGGU (1)
        $this->assertEquals(\App\Services\WorkflowService::STATUS_MENUNGGU, $kegiatan->status_utama_id);

        // 4. Post as Wadir to store simulating Wadir approval
        $response = $this->withSession([
            'user_id' => $wadir->user_id,
            'role' => 'wadir'
        ])->post("/wadir/kegiatan/store/{$kegiatan->kegiatan_id}", ['action' => 'approve']);

        $response->assertRedirect(route('wadir.dashboard'));
        $kegiatan->refresh();

        // Position advances to BENDAHARA (5)
        $this->assertEquals(\App\Services\WorkflowService::POSITION_BENDAHARA, $kegiatan->posisi_id);
        // Active status is reset to STATUS_MENUNGGU (1)
        $this->assertEquals(\App\Services\WorkflowService::STATUS_MENUNGGU, $kegiatan->status_utama_id);
    }

    /**
     * Test admin updating a proposal in revision status.
     */
    #[Test]
    #[TestDox('Memastikan admin berhasil mengajukan ulang usulan revisi, data diperbarui, dan status direset kembali ke Menunggu')]
    public function test_kegiatan_revision_update_works(): void
    {
        // 1. Create an Admin user
        $admin = User::create([
            'nama'         => 'Admin Revisi',
            'email'        => 'adminrevisi@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $admin->assignRole('Admin');

        // 2. Create a mock Kegiatan in STATUS_REVISI (2)
        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => 'Seminar Awal 2026',
            'prodi_penyelenggara' => 'D4 Teknik Informatika',
            'pemilik_kegiatan' => 'Admin Revisi',
            'nim_pelaksana' => '19200388273',
            'user_id' => $admin->user_id,
            'jurusan_penyelenggara' => 'Teknik Informatika dan Komputer',
            'status_utama_id' => \App\Services\WorkflowService::STATUS_REVISI,
            'wadir_tujuan' => 1,
            'posisi_id' => \App\Services\WorkflowService::POSITION_ADMIN,
        ]);

        $kak = Kak::create([
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'iku' => 'IKU 1',
            'gambaran_umum' => 'Gambaran awal',
            'penerima_manfaat' => 'Mahasiswa',
            'metode_pelaksanaan' => 'Online',
        ]);

        $kategori = \App\Models\KategoriRab::firstOrCreate(['nama_kategori' => 'Belanja Barang']);

        $oldRab = Rab::create([
            'kak_id' => $kak->kak_id,
            'kategori_id' => $kategori->kategori_rab_id,
            'uraian' => 'Kertas Kuno',
            'rincian' => '1 Rim',
            'vol1' => 1,
            'sat1' => 'Rim',
            'vol2' => 1,
            'sat2' => 'Rim',
            'harga' => 30000
        ]);

        // 3. Prepare mock request payload for revision update
        $rabDataJson = json_encode([
            'Belanja Barang' => [
                [
                    'uraian' => 'Kertas A4 HVS',
                    'rincian' => '2 Rim',
                    'vol1' => 2,
                    'sat1' => 'Rim',
                    'vol2' => 1,
                    'sat2' => 'Rim',
                    'harga' => 60000
                ]
            ]
        ]);

        $payload = [
            'nama_kegiatan' => 'Seminar Akhir Sukses 2026',
            'prodi' => 'D4 Teknik Informatika',
            'nama_pengusul' => 'Admin Revisi Baru',
            'nim_nip' => '19200388273',
            'jurusan' => 'Teknik Informatika dan Komputer',
            'wadir_tujuan' => 1,
            'indikator_kinerja' => 'Meningkatkan IKU 2',
            'gambaran_umum' => 'Gambaran akhir yang jelas sekali.',
            'penerima_manfaat' => 'Seluruh Mahasiswa TIK',
            'metode_pelaksanaan' => 'Hybrid',
            'tahapan' => [
                'Tahap revisi sukses',
            ],
            'indikator_nama' => [
                'Tingkat pemahaman materi',
            ],
            'indikator_bulan' => [
                3
            ],
            'indikator_target' => [
                95
            ],
            'rab_data' => $rabDataJson
        ];

        // 4. Submit PUT request
        $response = $this->withSession([
            'user_id' => $admin->user_id,
            'role' => 'admin'
        ])->put("/admin/pengajuan-usulan/update/{$kegiatan->kegiatan_id}", $payload);

        // 5. Assert redirect and success
        $response->assertRedirect(route('admin.usulan.index'));
        $response->assertSessionHas('success_message', 'Revisi usulan berhasil disimpan dan diajukan ulang!');

        // 6. Assert database was updated
        $kegiatan->refresh();
        $this->assertEquals('Seminar Akhir Sukses 2026', $kegiatan->nama_kegiatan);
        $this->assertEquals('Admin Revisi Baru', $kegiatan->pemilik_kegiatan);
        $this->assertEquals(\App\Services\WorkflowService::STATUS_MENUNGGU, $kegiatan->status_utama_id);
        $this->assertEquals(\App\Services\WorkflowService::POSITION_VERIFIKATOR, $kegiatan->posisi_id);

        $this->assertDatabaseHas('kaks', [
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'gambaran_umum' => 'Gambaran akhir yang jelas sekali.',
            'metode_pelaksanaan' => 'Hybrid'
        ]);

        $this->assertEquals('Meningkatkan IKU 2', $kegiatan->kak->iku);

        // Assert old RAB was deleted and new RAB was created
        $this->assertDatabaseMissing('rabs', [
            'uraian' => 'Kertas Kuno'
        ]);
        $this->assertDatabaseHas('rabs', [
            'kak_id' => $kak->kak_id,
            'uraian' => 'Kertas A4 HVS',
            'harga' => 60000,
            'vol1' => 2,
            'total_harga' => 120000
        ]);

        // Assert Indikator
        $this->assertDatabaseHas('indikator_kaks', [
            'kak_id' => $kak->kak_id,
            'indikator_keberhasilan' => 'Tingkat pemahaman materi',
            'bulan' => 3,
            'target_persen' => 95
        ]);

        // Assert Tahapan
        $this->assertDatabaseHas('tahapan_pelaksanaans', [
            'kak_id' => $kak->kak_id,
            'nama_tahapan' => 'Tahap revisi sukses'
        ]);

        // Assert Progress history
        $this->assertDatabaseHas('progress_histories', [
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'status_id' => \App\Services\WorkflowService::STATUS_MENUNGGU,
            'changed_by_user_id' => $admin->user_id
        ]);
    }

    /**
     * Test successful LPJ approval by Bendahara.
     */
    #[Test]
    #[TestDox('Memastikan bendahara berhasil menyetujui LPJ, memperbarui status LPJ dan kegiatan, serta menyimpan log')]
    public function test_bendahara_lpj_approval_works(): void
    {
        // 1. Create users
        $admin = User::create([
            'nama'         => 'Pengusul TI',
            'email'        => 'pengusullpj@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $admin->assignRole('Admin');

        $bendahara = User::create([
            'nama'         => 'Bendahara TI',
            'email'        => 'bendahara@example.com',
            'password'     => Hash::make('password123'),
            'nama_jurusan' => 'Teknik Informatika dan Komputer',
            'status'       => 'Aktif',
        ]);
        $bendahara->assignRole('Bendahara');

        // 2. Create a mock Kegiatan in status DANA_DIBERIKAN (5)
        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => 'Seminar LPJ 2026',
            'prodi_penyelenggara' => 'D4 Teknik Informatika',
            'pemilik_kegiatan' => 'Pengusul TI',
            'nim_pelaksana' => '19200388273',
            'user_id' => $admin->user_id,
            'jurusan_penyelenggara' => 'Teknik Informatika dan Komputer',
            'status_utama_id' => \App\Services\WorkflowService::STATUS_DANA_DIBERIKAN,
            'wadir_tujuan' => 1,
            'posisi_id' => \App\Services\WorkflowService::POSITION_BENDAHARA,
        ]);

        $kak = Kak::create([
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'iku' => 'IKU 1',
            'gambaran_umum' => 'Deskripsi.',
            'metode_pelaksanaan' => 'Online',
        ]);

        $kategori = \App\Models\KategoriRab::firstOrCreate(['nama_kategori' => 'Belanja Barang']);
        $rab = Rab::create([
            'kak_id' => $kak->kak_id,
            'kategori_id' => $kategori->kategori_rab_id,
            'uraian' => 'Kertas KVS',
            'rincian' => '1 Rim',
            'vol1' => 1,
            'sat1' => 'Rim',
            'vol2' => 1,
            'sat2' => 'Rim',
            'harga' => 40000
        ]);

        $lpj = \App\Models\Lpj::create([
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'status_id' => 1, // Menunggu Verifikasi
            'submitted_at' => now(),
            'tenggat_lpj' => now()->addDays(14)
        ]);

        $lpjItem = \App\Models\LpjItem::create([
            'lpj_id' => $lpj->lpj_id,
            'kategori_id' => $kategori->kategori_rab_id,
            'uraian' => 'Kertas KVS',
            'rincian' => '1 Rim',
            'total_harga' => 40000,
            'realisasi' => 40000,
            'sat1' => 'Rim',
            'vol1' => 1,
            'vol2' => 1,
            'harga' => 40000
        ]);

        // 3. Post to processes route simulating bendahara action=approve
        $payload = [
            'action' => 'approve',
            'notes' => 'Laporan lengkap dan valid.',
            'item_feedback' => [
                $rab->rab_item_id => 'Bukti kuitansi sudah jelas.'
            ]
        ];

        $response = $this->withSession([
            'user_id' => $bendahara->user_id,
            'role' => 'bendahara'
        ])->post("/bendahara/lpj/proses/{$kegiatan->kegiatan_id}", $payload);

        // 4. Assert response redirect to bendahara index
        $response->assertRedirect(route('bendahara.lpj.index'));
        $response->assertSessionHas('success', 'LPJ berhasil disetujui lunas.');

        // 5. Assert database updates
        $lpj->refresh();
        $this->assertEquals(3, $lpj->status_id); // Disetujui
        $this->assertNotNull($lpj->approved_at);

        $lpjItem->refresh();
        $this->assertEquals('Bukti kuitansi sudah jelas.', $lpjItem->komentar);

        $kegiatan->refresh();
        $this->assertEquals(6, $kegiatan->status_utama_id); // LPJ Disetujui

        // Assert Progress history for status 6
        $this->assertDatabaseHas('progress_histories', [
            'kegiatan_id' => $kegiatan->kegiatan_id,
            'status_id' => 6,
            'changed_by_user_id' => $bendahara->user_id
        ]);

        // Assert log_statuses contains approval log
        $this->assertDatabaseHas('log_statuses', [
            'user_id' => $admin->user_id,
            'tipe_log' => 'APPROVAL',
            'id_referensi' => $kegiatan->kegiatan_id
        ]);
    }
}
